### ISSUE TITLE
Jxplorer make wayland (and gnome) crash and get the user back to login screen

### ISSUE THREAD

**Issue by kadafax** [pegacat/jxplorer#6]
Hello,
On a fully updated ArchLinux, clicking on the "OK" button or "Cancel" when trying to connect to a ldap server make wayland (and thus gnome) crash and get the user back to the login screen.

Just before the crash, journactl print:
juil. 16 12:32:19 mycomputer org.gnome.Shell.desktop[3931]: starting JXplorer...
juil. 16 12:32:19 mycomputer org.gnome.Shell.desktop[3931]: Use "jxplorer.sh console" if you want logging to the console
juil. 16 12:32:19 mycomputer org.gnome.Shell.desktop[3931]: Window manager warning: Window 0x2c00020 sets an MWM hint indicating it isn't resizable, but sets min size 1 x 1 and max size 2147483647 x 2147483647; this doesn't make much sense.
juil. 16 12:32:19 mycomputer org.gnome.Shell.desktop[3931]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x2c00007 specified for 0x2c00020.
juil. 16 12:32:19 mycomputer org.gnome.Shell.desktop[3931]: Window manager warning: Window 0x2c00020 sets an MWM hint indicating it isn't resizable, but sets min size 1 x 1 and max size 2147483647 x 2147483647; this doesn't make much sense.

Jxplorer version: 3.3.1.2
Build from: https://github.com/pegacat/jxplorer/archive/v3.3.1.2.tar.gz
Java: jre8-openjdk 8.u222-2

**Comment by pegacat** [comment]
Hi Kadafax,

I don't believe this is JXplorer as such, rather I believe it's problems
with the java swing windowing library and open jdk :-/.  We've had problems
with openjdk in the past, and I'm afraid JX isn't tested against it.  The
'fix' is to use the Oracle version of java - any version after java 1.6
should be fine.

-----
*Dr Christopher Betts*
Pegacat Aerospace
Melbourne, Australia
m: 61 408 533 456

**Comment by kadafax** [comment]
Okay I'll try this.
Have a nice day
